name: Generate pac file

on:
  # push:
  workflow_dispatch:
  schedule:
    # 定时任务，在每天的N点执行任务(国际标准时间, 北京时间+8)
    - cron: "0 22 1 * *"

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.2.0

      - name: Setup python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.9.7"

      - name: Setup generate tool
        uses: BSFishy/pip-action@v1
        with:
          packages: genpac

      - name: Run generate tool
        run: genpac --format pac --user-rule-from ./rules.txt --pac-proxy "SOCKS5 127.0.0.1:51080" > ./pac.txt

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: "time: ${{ steps.date.outputs.date }} update pac.txt"
          add: pac.txt
          author_name: brinkqiang
          author_email: brink.qiang@gmail.com
          token: ${{ secrets.GITHUB_TOKEN }}
