name: Generate pac file

on:
  schedule:
    # 定时任务，在每天的N点执行任务(国际标准时间, 北京时间+8)
    - cron: 0 22 1 * *
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9.7"

      - run: python -m pip install --upgrade pip
      - run: pip install genpac
      - run: genpac --format pac --user-rule-from ./rules.txt --pac-proxy "PROXY 127.0.0.1:51080" > ./pac.txt

      - uses: josStorer/get-current-time@v2
        id: time
        with:
          format: yyyy-MM-DD

      - uses: EndBug/add-and-commit@v9
        if: github.event_name != 'pull_request'
        with:
          message: "chore: ${{ steps.time.outputs.formattedTime }} update pac.txt"
          add: pac.txt
          author_name: brinkqiang
          author_email: brink.qiang@gmail.com
          token: ${{ secrets.GITHUB_TOKEN }}
